{{- if eq .Values.environment "prod" }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: "cluster-external-secret"
spec:
  externalSecretName: "external-secret-greencity"
  namespaceSelector:
    matchLabels:
      # kubectl label namespace test Dev=test
      Dev: test

  refreshTime: "1m"

  externalSecretSpec:
    refreshInterval: "1m"

    secretStoreRef:
      name: cluster-secret-store
      kind: ClusterSecretStore

    target:
      name: greencity-secret
      creationPolicy: Owner

    data:
      - secretKey: AZURE-CLIENT-ID
        remoteRef:
          key: AZURE-CLIENT-ID

      - secretKey: AZURE-SECRET-ID
        remoteRef:
          key: AZURE-SECRET-ID

      - secretKey: AZURE-TENANT-ID
        remoteRef:
          key: AZURE-TENANT-ID

      - secretKey: KEY-VAULT-ENDPOINT
        remoteRef:
          key: KEY-VAULT-ENDPOINT

{{- end }}
