spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=${KEY_VAULT_ENDPOINT}

#Azure Connection
spring.cloud.azure.credential.client-id=${AZURE_CLIENT_ID}
spring.cloud.azure.credential.client-secret=${AZURE_SECRET_ID}
spring.cloud.azure.profile.tenant-id=${AZURE_TENANT_ID}

# Datasource
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximumPoolSize=${DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE}
server.port=8060

# Liquibase
spring.liquibase.url=${DATASOURCE_URL}
spring.liquibase.user=${DATASOURCE_USERNAME}
spring.liquibase.password=${DATASOURCE_PASSWORD}
spring.liquibase.enabled=${LIQUIBASE_ENABLED}
spring.liquibase.change-log=${LIQUIBASE_CHANGE_LOG}

# Hibernate
spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Mail sender
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE}

# Token settings
security.jwt.access-token.expiration-minutes=${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES}
security.jwt.refresh-token.expiration-minutes=${JWT_REFRESH_TOKEN_EXPIRATION_MINUTES}
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.verify-email.expiration-hours=${JWT_VERIFY_EMAIL_EXPIRATION_HOURS}
security.brute-force.max-attempts=${BRUTE_FORCE_MAX_ATTEMPTS}
security.brute-force.block-time-minutes=${BRUTE_FORCE_BLOCK_TIME_MINUTES}

# Cache
spring.cache.caffeine.spec=${CACHE_CAFFEINE_SPEC}

# File upload limit
spring.servlet.multipart.max-file-size=${MULTIPART_MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${MULTIPART_MAX_FILE_SIZE}
server.tomcat.max-http-form-post-size=${TOMCAT_MAX_HTTP_FORM_POST_SIZE}

#RestTemplate
greencity.server.address = ${GREENCITY_SERVER_ADDRESS}
greencityubs.server.address = ${GREENCITY_UBS_SERVER_ADDRESS}

#Thymeleaf
spring.web.resources.static-locations=classpath:/static/

#Swagger
springdoc.swagger-ui.doc-expansion=none

#AzureCloudStorage
azure.connection.string=${AZURE_CONNECTION_STRING}
azure.container.name=${AZURE_CONTAINER_NAME}

#WebClient
webclient.connection-timeout-millis=${WEBCLIENT_CONNECTION_TIMEOUT}
webclient.response-timeout-millis=${WEBCLIENT_RESPONSE_TIMEOUT}

#Client
client.address=${CLIENT_ADDRESS}

#External services / keys
external.google.api-key=${GOOGLE_API_KEY}

#Testers
testers.sign-in-token=${TESTERS_SIGN_IN_TOKEN}

contacts.sender.email-address=${SENDER_EMAIL_ADDRESS}
contacts.greenoffice.email-address=${GREEN_OFFICE_EMAIL_ADDRESS}
contacts.tgbot.feedbacks-email-address=${TG_BOT_FEEDBACKS_EMAIL_ADDRESS}
contacts.authorization.system-email-address=${SYSTEM_EMAIL_ADDRESS}

# Time after a user last activity time to check if a user is online
greencity.time.after.last.activity=60000

#WebSockets
spring.messaging.stomp.websocket.allowed-origins=\
 https://www.greencity.cx.ua, \
  https://www.greencity.cx.ua/, \
  https://www.greencity.cx.ua/*, \
  https://greencity.greencity.cx.ua, \
  https://greencity.greencity.cx.ua/, \
  https://greencity.greencity.cx.ua/*, \
  https://greencity-user.greencity.cx.ua, \
  https://greencity-user.greencity.cx.ua/, \
  https://greencity-user.greencity.cx.ua/*, \
  https://www.pick-up.city, \
  https://www.pick-up.city/, \
  https://www.pick-up.city/*, \
  http://localhost:4200, \
  http://localhost:4200/, \
  http://localhost:4200/*, \
  http://localhost:4205, \
  http://localhost:4200/, \
  http://localhost:4205/*

#Googleapis
google.resource.userInfoUri=https://www.googleapis.com/oauth2/v3/userinfo?access_token=

spring.liquibase.parameters.service-email=${SYSTEM_EMAIL_ADDRESS}